# Generated by Django 3.2.4 on 2021-07-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_allimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllImages',
        ),
    ]
